services:
  alm-frontend:
    container_name: alm-bannari-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_FRONTEND_URL: ${VITE_FRONTEND_URL}
        VITE_API_PORT: ${VITE_API_PORT:-}
        VITE_RESERVED_SUBDOMAINS: ${VITE_RESERVED_SUBDOMAINS:-web,www,api,pressanaorg,bannari}
    ports:
      - "3004:80"
    restart: unless-stopped
