import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import API from "../lib/axios";
import ProductSupplyForm from "./ProductSupplyForm";
import ServiceSupplyForm from "./ServiceSupplyForm";
import { useAuthStore } from "../store/useAuthStore";
import { v4 as uuidv4 } from "uuid";
import { generateUUID } from '../utils/uuid';
import { toast } from "react-hot-toast";
import { useLanguage } from "../contexts/LanguageContext";


const AddEntityForm = () => {
  const navigate = useNavigate();
  const user = useAuthStore((state) => state.user);
  const org_id = user?.org_id || "";
  const { t } = useLanguage();

  const [form, setForm] = useState({
    vendor_id: "", // Will be generated by backend
    org_id: org_id,
    vendor_name: "",
    int_status: 1,
    company_name: "",
    address_line1: "",
    address_line2: "",
    city: "",
    state: "",
    pincode: "",
    company_email: "",
    gst_number: "",
    cin_number: "",
    contact_person_name: "",
    contact_person_email: "",
    contact_person_number: "", // Added this required field
    contract_start_date: "",
    contract_end_date: "",
    created_by: "admin",
    created_on: null, // Will be set by backend
    changed_by: "admin",
    changed_on: null, // Will be set by backend
    product_supply: false, // Additional fields for UI
    service_supply: false,
  });

  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState("Vendor Details");
  const [createdVendorId, setCreatedVendorId] = useState(""); // Store generated vendor_id
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const [vendorSaved, setVendorSaved] = useState(false); // Track if vendor has been saved
  const [savingTab, setSavingTab] = useState(""); // Track which tab is currently saving
  const [savedTabs, setSavedTabs] = useState(new Set()); // Track which tabs have been saved
  const [uploadRows, setUploadRows] = useState([]); // {id,type,docTypeName,file,previewUrl}
  const [isUploading, setIsUploading] = useState(false);
  const [documentTypes, setDocumentTypes] = useState([]);
  const [slaDescriptions, setSlaDescriptions] = useState([]);
  const [selectedSLAs, setSelectedSLAs] = useState([]); // Array of {sla_id, description, value, index}
  const [slaDropdownValue, setSlaDropdownValue] = useState(''); // Controlled value for SLA dropdown

  // Debug: Log when selectedSLAs changes
  useEffect(() => {
    console.log('[AddEntityForm] selectedSLAs state updated:', selectedSLAs);
    console.log('[AddEntityForm] Number of selected SLAs:', selectedSLAs.length);
  }, [selectedSLAs]);

  // Fetch document types and SLA descriptions on component mount
  useEffect(() => {
    fetchDocumentTypes();
    fetchSLADescriptions();
  }, []);

  const fetchDocumentTypes = async () => {
    try {
      console.log('Fetching document types for vendors...');
      const res = await API.get('/doc-type-objects/object-type/vendor');
      console.log('Document types response:', res.data);

      if (res.data && res.data.success && Array.isArray(res.data.data)) {
        // Transform API data to dropdown format
        const docTypes = res.data.data.map(docType => ({
          id: docType.dto_id,  // Use dto_id instead of doc_type
          text: docType.doc_type_text,
          doc_type: docType.doc_type  // Keep doc_type for reference
        }));
        setDocumentTypes(docTypes);
        console.log('Document types loaded:', docTypes);
      } else {
        console.log('No document types found, using fallback');
        setDocumentTypes([]);
      }
    } catch (err) {
      console.error('Error fetching document types:', err);
      toast.error(t('vendors.failedToLoadDocumentTypes'));
      setDocumentTypes([]);
    }
  };

  const fetchSLADescriptions = async () => {
    try {
      console.log('Fetching SLA descriptions...');
      const res = await API.get('/sla-descriptions');
      console.log('SLA descriptions response:', res.data);

      if (res.data && res.data.success && Array.isArray(res.data.data)) {
        console.log(`Loaded ${res.data.data.length} SLA descriptions:`, res.data.data);
        setSlaDescriptions(res.data.data);
        console.log('SLA descriptions loaded:', res.data.data);
      } else {
        console.warn('No SLA descriptions found or invalid response format:', res.data);
        setSlaDescriptions([]);
        toast.error('No SLA descriptions found in database');
      }
    } catch (err) {
      console.error('Error fetching SLA descriptions:', err);
      console.error('Error details:', err.response?.data || err.message);
      toast.error(err.response?.data?.message || 'Failed to load SLA descriptions. Please check if tblSLA_Desc table exists.');
      setSlaDescriptions([]);
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));

    // Reset submit attempted state when user starts typing
    if (submitAttempted) {
      setSubmitAttempted(false);
    }

    // Uncheck disables tab
    if (
      type === "checkbox" &&
      !checked &&
      activeTab ===
        (name === "product_supply"
          ? "Product Details"
          : name === "service_supply"
          ? "Service Details"
          : "")
    ) {
      setActiveTab("Vendor Details");
    }
  };

  // Handle SLA selection from dropdown
  const handleSLASelect = (e) => {
    const selectedSlaId = e.target.value;
    console.log('[AddEntityForm] handleSLASelect called with value:', selectedSlaId);
    
    if (!selectedSlaId || selectedSlaId === '') {
      console.log('[AddEntityForm] Empty value, returning');
      return;
    }
    
    const selectedSLA = slaDescriptions.find(sla => sla.sla_id === selectedSlaId);
    if (!selectedSLA) {
      console.warn('[AddEntityForm] Selected SLA not found in slaDescriptions:', selectedSlaId);
      e.target.value = '';
      return;
    }
    
    console.log('[AddEntityForm] Found SLA in descriptions:', selectedSLA);
    
    // Use functional update to check if already selected
    setSelectedSLAs(prev => {
      // Check if already selected
      if (prev.find(s => s.sla_id === selectedSlaId)) {
        console.warn('[AddEntityForm] SLA already exists:', selectedSlaId);
        toast.error('This SLA is already selected');
        e.target.value = '';
        return prev;
      }
      
      // Add to selectedSLAs with next available index (1-10)
      const nextIndex = prev.length + 1;
      if (nextIndex > 10) {
        toast.error('Maximum 10 SLAs can be selected');
        e.target.value = '';
        return prev;
      }
      
      const newSLA = {
        sla_id: selectedSLA.sla_id,
        description: selectedSLA.description,
        value: '',
        index: nextIndex
      };
      
      console.log('[AddEntityForm] Adding SLA to selectedSLAs:', newSLA);
      console.log('[AddEntityForm] Current selectedSLAs before update:', prev);
      
      const updated = [...prev, newSLA];
      console.log('[AddEntityForm] Updated selectedSLAs array:', updated);
      console.log('[AddEntityForm] Updated array length:', updated.length);
      
      // Reset dropdown after state update
      setTimeout(() => {
        e.target.value = '';
      }, 0);
      
      return updated;
    });
  };
  
  // Handle SLA value input change
  const handleSLAValueChange = (slaId, value) => {
    setSelectedSLAs(prev => prev.map(sla => 
      sla.sla_id === slaId ? { ...sla, value } : sla
    ));
  };
  
  // Remove selected SLA
  const handleRemoveSLA = (slaId) => {
    setSelectedSLAs(prev => {
      const filtered = prev.filter(sla => sla.sla_id !== slaId);
      // Re-index remaining SLAs
      return filtered.map((sla, idx) => ({ ...sla, index: idx + 1 }));
    });
  };
  
  // Map selected SLAs to vendor_slas array for backend
  const mapSLAsToForm = () => {
    const mapped = selectedSLAs
      .filter(sla => sla.value && sla.value.trim()) // Only include SLAs with values
      .map(sla => ({
        sla_id: sla.sla_id, // e.g., "SLA-1", "SLA-2", etc. from tblsla_desc
        value: sla.value
      }));
    console.log('[AddEntityForm] Mapped SLAs for backend:', mapped);
    return mapped;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitAttempted(true);
    try {
      setLoading(true);
      setSavingTab("Vendor Details");
      
      // Map selected SLAs to vendor_slas array
      const vendor_slas = mapSLAsToForm();
      const formDataWithSLAs = { ...form, vendor_slas };
      
      const response = await API.post("/create-vendor", formDataWithSLAs); // Backend adds ext_id, created_on, org_id
      const vendorId = response.data?.data?.vendor_id;
      setCreatedVendorId(vendorId || "");
      setVendorSaved(true); // Mark vendor as saved
      setSavedTabs(prev => new Set([...prev, "Vendor Details"])); // Mark vendor tab as saved
      toast.success(t('vendors.vendorCreatedSuccessfully'));
      // Optionally: navigate("/master-data/vendors");
    } catch (error) {
      console.error(error);
      const errorMessage = error.response?.data?.message || error.response?.data?.error || t('vendors.failedToCreateVendor');
      toast.error(errorMessage);
    } finally {
      setLoading(false);
      setSavingTab("");
    }
  };

  // Validation function for required fields based on database constraints
  const validateRequiredFields = () => {
    // Based on typical vendor table constraints and business logic
    const requiredFields = [
      { name: 'vendor_name', label: 'Vendor Name' },
      { name: 'company_name', label: 'Company Name' },
      { name: 'company_email', label: 'Company Email' },
      { name: 'contact_person_name', label: 'Contact Person Name' },
      { name: 'contact_person_number', label: 'Contact Number' }
    ];

    const errors = [];
    
    requiredFields.forEach(field => {
      if (!form[field.name] || !form[field.name].trim()) {
        errors.push(`${field.label} is required`);
      }
    });

    // Email validation
    if (form.company_email && form.company_email.trim()) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(form.company_email.trim())) {
        errors.push('Please enter a valid email address');
      }
    }

    // Contact person email validation (if provided)
    if (form.contact_person_email && form.contact_person_email.trim()) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(form.contact_person_email.trim())) {
        errors.push('Please enter a valid contact person email address');
      }
    }

    // Phone number validation (basic format check)
    if (form.contact_person_number && form.contact_person_number.trim()) {
      const phoneRegex = /^[\+]?[0-9\s\-\(\)]{10,}$/;
      if (!phoneRegex.test(form.contact_person_number.trim())) {
        errors.push('Please enter a valid contact number (at least 10 digits)');
      }
    }

    return errors;
  };

  // Unified save function - saves all applicable tabs
  const handleUnifiedSave = async () => {
    try {
      setLoading(true);
      
      // Always try to save vendor details first if not already saved
      let vendorSaveSuccess = vendorSaved;
      if (!vendorSaved) {
        // Validate required fields before saving
        const validationErrors = validateRequiredFields();
        if (validationErrors.length > 0) {
          setSubmitAttempted(true); // Trigger field highlighting
          toast.error(`Please fill required fields: ${validationErrors.join(', ')}`);
          setLoading(false); // Reset loading state
          return;
        }
        
        setSavingTab("Vendor Details");
        try {
          await handleSubmit({ preventDefault: () => {} });
          vendorSaveSuccess = true; // Mark as successful if no error thrown
        } catch (error) {
          vendorSaveSuccess = false;
          throw error; // Re-throw to be caught by outer catch
        }
      }
      
      // Only proceed with other tabs if vendor was successfully saved
      if (!vendorSaveSuccess) {
        setLoading(false);
        return;
      }
      
      // Now save other tabs if they have data and vendor is saved
      const tabsToSave = [];
      
      // Check Product Details tab
      if (form.product_supply && !savedTabs.has("Product Details")) {
        const productsFromStorage = JSON.parse(sessionStorage.getItem('products') || '[]');
        if (Array.isArray(productsFromStorage) && productsFromStorage.length > 0) {
          tabsToSave.push("Product Details");
        }
      }
      
      // Check Service Details tab
      if (form.service_supply && !savedTabs.has("Service Details")) {
        const servicesFromStorage = JSON.parse(sessionStorage.getItem('services') || '[]');
        if (Array.isArray(servicesFromStorage) && servicesFromStorage.length > 0) {
          tabsToSave.push("Service Details");
        }
      }
      
      // Check Attachments tab
      if (!savedTabs.has("Attachments") && uploadRows.length > 0) {
        tabsToSave.push("Attachments");
      }
      
      // Save each tab that has data
      for (const tabName of tabsToSave) {
        if (tabName === "Product Details") {
          setSavingTab("Product Details");
          // Trigger the save in ProductSupplyForm
          // Wait for the save operation to complete
          await new Promise(resolve => setTimeout(resolve, 3000));
        } else if (tabName === "Service Details") {
          setSavingTab("Service Details");
          // Trigger the save in ServiceSupplyForm
          // Wait for the save operation to complete
          await new Promise(resolve => setTimeout(resolve, 3000));
        } else if (tabName === "Attachments") {
          setSavingTab("Attachments");
          await handleBatchUpload();
        }
      }
      
      // Show success message only if we actually saved something
      if (vendorSaveSuccess || tabsToSave.length > 0) {
        const savedTabsList = tabsToSave.length > 0 ? tabsToSave.join(", ") : "Vendor Details";
        toast.success(`Successfully saved: ${savedTabsList}`);
      }
      
    } catch (error) {
      console.error('Error in unified save:', error);
      toast.error(t('vendors.saveFailed') || 'Save failed');
    } finally {
      setLoading(false);
      setSavingTab("");
    }
  };

  // Unified cancel function
  const handleUnifiedCancel = () => {
    navigate("/master-data/vendors");
  };

  // Callback to mark tabs as saved
  const markTabAsSaved = (tabName) => {
    setSavedTabs(prev => new Set([...prev, tabName]));
  };

  const tabs = ["Vendor Details"];
  if (form.product_supply) tabs.push("Product Details");
  if (form.service_supply) tabs.push("Service Details");
  tabs.push("Attachments");

  // Function to translate tab names
  const translateTab = (tab) => {
    switch(tab) {
      case "Vendor Details": return t('vendors.vendorDetails');
      case "Product Details": return t('vendors.productDetails');
      case "Service Details": return t('vendors.serviceDetails');
      case "Attachments": return t('vendors.attachments');
      default: return tab;
    }
  };

  // Helper for invalid field
  const isFieldInvalid = (val) => submitAttempted && (!val || !val.trim());

  // Handle batch upload for vendor documents
  const handleBatchUpload = async () => {
    if (uploadRows.length === 0) {
      toast.error(t('vendors.addAtLeastOneFile'));
      return;
    }

    // Check if vendor has been created
    if (!createdVendorId) {
      toast.error(t('vendors.pleaseCreateVendorFirst'));
      return;
    }

    // Validate all attachments
    for (const r of uploadRows) {
      if (!r.type || !r.file) {
        toast.error(t('vendors.selectDocumentTypeAndFile'));
        return;
      }
      // Check if the selected document type requires a custom name
      const selectedDocType = documentTypes.find(dt => dt.id === r.type);
      if (selectedDocType && (selectedDocType.text.toLowerCase().includes('other') || selectedDocType.doc_type === 'OT') && !r.docTypeName?.trim()) {
        toast.error(t('vendors.enterCustomNameForDocuments', { type: selectedDocType.text }));
        return;
      }
    }

    setIsUploading(true);
    let successCount = 0;
    let failCount = 0;

    try {
      for (const r of uploadRows) {
        try {
          const fd = new FormData();
          fd.append('file', r.file);
          fd.append('vendor_id', createdVendorId); // Add vendor_id
          fd.append('dto_id', r.type);  // Send dto_id instead of doc_type
          if (r.type && r.docTypeName?.trim()) {
            fd.append('doc_type_name', r.docTypeName);
          }
          
          // Upload the file to the vendor document API
          await API.post('/vendor-docs/upload', fd, { 
            headers: { 'Content-Type': 'multipart/form-data' }
          });
          successCount++;
        } catch (err) {
          console.error('Failed to process file:', r.file.name, err);
          failCount++;
        }
      }

      if (successCount > 0) {
        if (failCount === 0) {
          toast.success(t('vendors.allFilesUploadedSuccessfully'));
          markTabAsSaved("Attachments"); // Mark attachments tab as saved
        } else {
          toast.success(t('vendors.filesUploadedWithFailures', { successCount, failCount }));
        }
        setUploadRows([]); // Clear attachments after successful upload
      } else {
        toast.error(t('vendors.failedToUploadAnyFiles'));
      }
    } catch (err) {
      console.error('Process error:', err);
      toast.error(t('vendors.uploadProcessFailed'));
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto mt-1 bg-white shadow rounded">
      {/* Card Header */}
      <div className="bg-[#0E2F4B] text-white py-3 px-6 rounded-t border-b-4 border-[#FFC107] flex justify-center items-center">
        {/* <span className="text-2xl font-semibold text-center w-full">Vendor Details</span> */}
      </div>

      <div className="px-8 pt-8">
        {/* Tabs */}
        <div className="flex border-b border-gray-200 mb-8">
          {tabs.map((tab) => (
            <button
              key={tab}
              className={`px-6 py-2 -mb-px font-semibold text-base border-b-2 focus:outline-none transition-all relative ${
                activeTab === tab
                  ? "border-[#0E2F4B] text-[#0E2F4B] bg-white"
                  : "border-transparent text-gray-500 bg-transparent"
              }`}
              onClick={() => setActiveTab(tab)}
              type="button"
            >
              <span className="flex items-center">
                {translateTab(tab)}
                {savedTabs.has(tab) && (
                  <svg className="w-4 h-4 ml-2 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                  </svg>
                )}
              </span>
            </button>
          ))}
        </div>

        {/* Tab Content */}
        {activeTab === "Vendor Details" && (
          <form onSubmit={handleSubmit}>
            <div className="grid grid-cols-3 gap-6 mb-6">
                              {/* <FormInput label="Vendor Id" name="vendor_id" value={createdVendorId} readOnly /> */}
                <FormInput label={t('vendors.vendorName')} name="vendor_name" value={form.vendor_name} onChange={handleInputChange} required isInvalid={isFieldInvalid(form.vendor_name)} placeholder={t('vendors.enterVendorName')} />
                <FormInput label={t('vendors.company')} name="company_name" value={form.company_name} onChange={handleInputChange} required isInvalid={isFieldInvalid(form.company_name)} placeholder={t('vendors.enterCompanyName')} />
                <FormInput label={t('vendors.companyEmail')} name="company_email" value={form.company_email} onChange={handleInputChange} type="email" required isInvalid={isFieldInvalid(form.company_email)} placeholder={t('vendors.enterCompanyEmail')} />
              </div>

              <div className="grid grid-cols-3 gap-6 mb-6">
                <FormInput label={t('vendors.contactNumber')} name="contact_person_number" value={form.contact_person_number} onChange={handleInputChange} required isInvalid={isFieldInvalid(form.contact_person_number)} placeholder={t('vendors.enterContactNumber')} />
              <FormInput label={t('vendors.gstNumber')} name="gst_number" value={form.gst_number} onChange={handleInputChange} placeholder={t('vendors.enterGstNumber')} />
              <FormInput label={t('vendors.cinNumber')} name="cin_number" value={form.cin_number} onChange={handleInputChange} placeholder={t('vendors.enterCinNumber')} />
            </div>

            {/* Optional Address/Contact Fields */}
            <div className="grid grid-cols-3 gap-6 mb-6">
              <FormInput label={t('vendors.addressLine1')} name="address_line1" value={form.address_line1} onChange={handleInputChange} placeholder={t('vendors.enterAddressLine1')} />
              <FormInput label={t('vendors.city')} name="city" value={form.city} onChange={handleInputChange} placeholder={t('vendors.enterCity')} />
              <FormInput label={t('vendors.state')} name="state" value={form.state} onChange={handleInputChange} placeholder={t('vendors.enterState')} />
            </div>

            <div className="grid grid-cols-3 gap-6 mb-6">
              <FormInput label={t('vendors.pincode')} name="pincode" value={form.pincode} onChange={handleInputChange} placeholder={t('vendors.enterPincode')} />
              <FormInput label={t('vendors.contactPerson')} name="contact_person_name" value={form.contact_person_name} onChange={handleInputChange} required isInvalid={isFieldInvalid(form.contact_person_name)} placeholder={t('vendors.enterContactPersonName')} />
              <FormInput label={t('vendors.contactEmail')} name="contact_person_email" value={form.contact_person_email} onChange={handleInputChange} type="email" placeholder={t('vendors.enterContactPersonEmail')} />
            </div>

            {/* Contract Dates */}
            <div className="grid grid-cols-2 gap-6 mb-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Contract Start Date
                </label>
                <input
                  type="date"
                  name="contract_start_date"
                  value={form.contract_start_date}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Contract End Date
                </label>
                <input
                  type="date"
                  name="contract_end_date"
                  value={form.contract_end_date}
                  onChange={handleInputChange}
                  className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                />
              </div>
            </div>

            {/* SLA Fields Section */}
            {slaDescriptions.length > 0 && (
              <div className="mb-6">
                <h3 className="text-lg font-semibold text-gray-800 mb-4">SLA Fields</h3>
                
                {/* SLA Dropdown */}
                <div className="mb-4">
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Select SLA
                  </label>
              <select
                onChange={handleSLASelect}
                className="w-64 px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                value=""
                key={`sla-dropdown-${selectedSLAs.length}`}
              >
                <option value="" disabled hidden>Select an SLA</option>
                {slaDescriptions
                  .filter(sla => !selectedSLAs.find(s => s.sla_id === sla.sla_id))
                  .map((sla) => (
                    <option key={sla.sla_id} value={sla.sla_id}>
                      {sla.description}
                    </option>
                  ))}
              </select>
                </div>

                {/* Selected SLAs with Input Fields */}
                <div className="space-y-3" key={`sla-container-${selectedSLAs.length}`}>
                  {selectedSLAs.length === 0 && (
                    <p className="text-sm text-gray-500 italic">No SLAs selected. Select an SLA from the dropdown above.</p>
                  )}
                  {selectedSLAs.map((sla, idx) => {
                    // Use a stable key based on sla_id and index - ensure it's unique
                    const uniqueKey = `sla-input-${sla.sla_id}-${idx}`;
                    console.log('[AddEntityForm] Rendering SLA input field #' + (idx + 1) + ':', {
                      sla_id: sla.sla_id,
                      description: sla.description,
                      value: sla.value,
                      index: sla.index,
                      key: uniqueKey,
                      arrayIndex: idx,
                      totalSelected: selectedSLAs.length
                    });
                    return (
                      <div key={uniqueKey} className="flex items-center gap-3 p-3 border border-gray-300 rounded-lg bg-gray-50">
                        <div className="flex-1">
                          <label className="block text-sm font-medium text-gray-700 mb-1">
                            {sla.description || sla.sla_id}
                          </label>
                          <input
                            type="text"
                            name={`sla-input-${sla.sla_id}`}
                            id={`sla-input-${sla.sla_id}-${idx}`}
                            value={sla.value || ''}
                            onChange={(e) => {
                              console.log('[AddEntityForm] Input changed for:', sla.sla_id, 'new value:', e.target.value);
                              handleSLAValueChange(sla.sla_id, e.target.value);
                            }}
                            placeholder="Enter in hr"
                            className="w-full px-4 py-2 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                          />
                        </div>
                        <button
                          type="button"
                          onClick={() => {
                            console.log('[AddEntityForm] Removing SLA:', sla.sla_id);
                            handleRemoveSLA(sla.sla_id);
                          }}
                          className="px-3 py-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                          title="Remove SLA"
                        >
                          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Checkboxes */}
            <div className="flex flex-col gap-3 mb-10 pl-2">
              <FormCheckbox label={t('vendors.productSupply')} name="product_supply" checked={form.product_supply} onChange={handleInputChange} />
              <FormCheckbox label={t('vendors.serviceSupply')} name="service_supply" checked={form.service_supply} onChange={handleInputChange} />
            </div>

          </form>
        )}

        {activeTab === "Product Details" && <ProductSupplyForm vendorId={createdVendorId} orgId={org_id} vendorSaved={vendorSaved} onSaveTrigger={savingTab} onTabSaved={markTabAsSaved} />}
        {activeTab === "Service Details" && <ServiceSupplyForm vendorId={createdVendorId} orgId={org_id} vendorSaved={vendorSaved} onSaveTrigger={savingTab} onTabSaved={markTabAsSaved} />}
        
        {/* Hidden components for save operations - rendered but not visible */}
        {activeTab !== "Product Details" && form.product_supply && JSON.parse(sessionStorage.getItem('products') || '[]').length > 0 && (
          <div style={{ display: 'none' }}>
            <ProductSupplyForm vendorId={createdVendorId} orgId={org_id} vendorSaved={vendorSaved} onSaveTrigger={savingTab} onTabSaved={markTabAsSaved} />
          </div>
        )}
        {activeTab !== "Service Details" && form.service_supply && JSON.parse(sessionStorage.getItem('services') || '[]').length > 0 && (
          <div style={{ display: 'none' }}>
            <ServiceSupplyForm vendorId={createdVendorId} orgId={org_id} vendorSaved={vendorSaved} onSaveTrigger={savingTab} onTabSaved={markTabAsSaved} />
          </div>
        )}
        {activeTab === "Attachments" && (
          <div className="pb-8">
            {/* Header row: Add File button */}
            <div className="mb-4 flex items-end gap-3">
              <div></div>
            </div>

            <div className="mb-4 flex items-center justify-between">
              <div className="text-lg font-semibold">{t('vendors.attachments')}</div>
              <button 
                type="button" 
                onClick={() => setUploadRows(prev => ([...prev, { id: generateUUID(), type:'', docTypeName:'', file:null, previewUrl:'' }]))}
                className="h-[38px] px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 inline-flex items-center"
              >
                <svg className="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                </svg>
                {t('vendors.addFile')}
              </button>
            </div>

            <div className="text-sm text-gray-600 mb-3">
              {t('vendors.documentTypesLoadedFromSystem')}
              {!createdVendorId && (
                <span className="text-amber-600 font-medium ml-2">
                  ⚠️ {t('vendors.pleaseCreateVendorFirstBeforeUploading')}
                </span>
              )}
            </div>

            {uploadRows.length === 0 ? (
              <div className="text-sm text-gray-500">{t('vendors.noFilesAdded')}</div>
            ) : (
              <div className="space-y-3">
                {uploadRows.map(r => (
                  <div key={r.id} className="grid grid-cols-6 gap-3 items-start bg-white border border-gray-200 rounded p-3">
                    <div className="col-span-2">
                      <label className="block text-xs font-medium mb-1">{t('vendors.documentType')}</label>
                      <select 
                        className="w-full border rounded px-2 py-2 text-sm h-[38px]" 
                        value={r.type} 
                        onChange={e => setUploadRows(prev => prev.map(x => x.id===r.id?{...x,type:e.target.value}:x))}
                      >
                        <option value="">{t('vendors.selectType')}</option>
                        {documentTypes.map(docType => (
                          <option key={docType.id} value={docType.id}>
                            {docType.text}
                          </option>
                        ))}
                      </select>
                    </div>

                    {(() => {
                      const selectedDocType = documentTypes.find(dt => dt.id === r.type);
                      const needsCustomName = selectedDocType && (selectedDocType.text.toLowerCase().includes('other') || selectedDocType.doc_type === 'OT');
                      return needsCustomName && (
                        <div className="col-span-2">
                          <label className="block text-xs font-medium mb-1">{t('vendors.customName')}</label>
                          <input
                            className="w-full border rounded px-2 py-2 text-sm h-[38px]"
                            value={r.docTypeName}
                            onChange={e => setUploadRows(prev => prev.map(x => x.id===r.id?{...x,docTypeName:e.target.value}:x))}
                            placeholder={`${t('vendors.enterCustomNameFor')} ${selectedDocType?.text}`}
                          />
                        </div>
                      );
                    })()}

                    <div className={(() => {
                      const selectedDocType = documentTypes.find(dt => dt.id === r.type);
                      const needsCustomName = selectedDocType && (selectedDocType.text.toLowerCase().includes('other') || selectedDocType.doc_type === 'OT');
                      return needsCustomName ? 'col-span-3' : 'col-span-4';
                    })()}>
                      <label className="block text-xs font-medium mb-1">{t('vendors.fileMax10MB')}</label>
                      <div className="flex items-center gap-2">
                        <div className="relative flex-1 max-w-md">
                          <input
                            type="file"
                            id={`file-${r.id}`}
                            onChange={e => {
                              const f = e.target.files?.[0] || null;
                              if (f && f.size > 15 * 1024 * 1024) { // 15MB limit
                                toast.error(t('vendors.fileSizeExceeds15MB'));
                                e.target.value = '';
                                return;
                              }
                              const previewUrl = f ? URL.createObjectURL(f) : '';
                              setUploadRows(prev => prev.map(x => x.id===r.id?{...x,file:f,previewUrl}:x));
                            }}
                            className="hidden"
                          />
                          <label
                            htmlFor={`file-${r.id}`}
                            className="flex items-center h-[38px] px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 cursor-pointer w-full"
                          >
                            <svg className="flex-shrink-0 w-5 h-5 mr-2 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                            </svg>
                            <span className="truncate max-w-[200px] inline-block">
                              {r.file ? r.file.name : t('vendors.chooseFile')}
                            </span>
                          </label>
                        </div>
                        {r.previewUrl && (
                          <a 
                            href={r.previewUrl} 
                            target="_blank" 
                            rel="noreferrer" 
                            className="h-[38px] inline-flex items-center px-4 bg-[#0E2F4B] text-white rounded-md shadow-sm text-sm font-medium hover:bg-[#1a4971] transition-colors"
                          >
                            <svg className="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                            </svg>
                            {t('vendors.preview')}
                          </a>
                        )}
                        <button 
                          type="button" 
                          onClick={() => setUploadRows(prev => prev.filter(x => x.id!==r.id))}
                          className="h-[38px] inline-flex items-center px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 transition-colors"
                        >
                          <svg className="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                          </svg>
                          {t('vendors.remove')}
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}

          </div>
        )}
      </div>

      {/* Unified Save and Cancel Buttons */}
      <div className="px-8 pb-8">
        <div className="flex justify-end gap-3 border-t border-gray-200 pt-6">
          <button
            type="button"
            onClick={handleUnifiedCancel}
            className="bg-gray-300 text-gray-700 px-8 py-2 rounded text-base font-medium hover:bg-gray-400 transition"
            disabled={loading}
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleUnifiedSave}
            className="bg-[#002F5F] text-white px-8 py-2 rounded text-base font-medium hover:bg-[#0E2F4B] transition"
            disabled={loading}
          >
            {loading ? (
              <span className="flex items-center">
                <svg className="animate-spin h-4 w-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                {savingTab ? `Saving ${savingTab}...` : 'Saving...'}
              </span>
            ) : (
              'Save All'
            )}
          </button>
        </div>
        
        {/* Status indicator */}
        {vendorSaved && (
          <div className="mt-2 text-sm text-green-600 flex items-center">
            <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
            </svg>
            Vendor details saved successfully
          </div>
        )}
      </div>
    </div>
  );
};

// Reusable input component
const FormInput = ({ label, name, value, onChange, required = false, type = "text", readOnly = false, isInvalid = false, placeholder }) => (
  <div>
    <label className="block text-sm font-medium mb-1 text-gray-700">
      {label} {required && <span className="text-red-500">*</span>}
    </label>
    <input
      type={type}
      name={name}
      value={value}
      onChange={onChange}
      required={required}
      readOnly={readOnly}
      className={`w-full px-3 py-2 border rounded text-sm ${readOnly ? 'bg-gray-200 text-gray-700 cursor-not-allowed' : 'bg-white'} ${isInvalid ? 'border-red-500' : 'border-gray-300'} ${readOnly && name === 'vendor_id' ? 'focus:ring-0 focus:border-gray-300 hover:border-gray-300' : 'focus:outline-none focus:ring-2 focus:ring-[#0E2F4B]'}`}
      placeholder={name === 'vendor_id' && !value ? 'Will be generated' : placeholder || label}
      tabIndex={readOnly ? -1 : 0}
    />
  </div>
);

const FormCheckbox = ({ label, name, checked, onChange }) => (
  <label className="inline-flex items-center text-gray-700 text-base font-medium">
    <input
      type="checkbox"
      name={name}
      checked={checked}
      onChange={onChange}
      className="mr-2 w-4 h-4 accent-[#0E2F4B]"
    />
    {label}
  </label>
);

export default AddEntityForm;
