import { normalizeAppId } from './accessLevel';

/** Shared app_id → route map (keep in sync with DatabaseSidebar). */
export const APP_ID_TO_PATH = {
  DASHBOARD: '/dashboard',
  ASSETS: '/assets',
  ADDASSET: '/assets/add',
  ASSETASSIGNMENT: '/assign-department-assets',
  COSTCENTERTRANSFER: '/cost-center-transfer',
  VENDORS: '/master-data/vendors',
  INSPECTIONCHECKLISTS: '/master-data/inspection-checklists',
  INSPECTIONFREQUENCY: '/master-data/inspection-frequency',
  ASSETTYPECHECKLISTMAPPING: '/master-data/asset-type-checklist-mapping',
  DEPTASSIGNMENT: '/assign-department-assets',
  EMPASSIGNMENT: '/assign-employee-assets',
  WORKORDERMANAGEMENT: '/workorder-management',
  INSPECTION: '/inspection-view',
  INSPECTIONVIEW: '/inspection-view',
  INSPECTIONAPPROVAL: '/inspection-approval',
  MAINTENANCEAPPROVAL: '/maintenance-approval',
  VENDORRENEWALAPPROVAL: '/vendor-renewal-approval',
  SCRAPMAINTENANCEAPPROVAL: '/scrap-approval',
  SUPERVISORAPPROVAL: '/maintenance-list',
  REPORTBREAKDOWN: '/report-breakdown',
  'EMPLOYEE REPORT BREAKDOWN': '/employee-report-breakdown',
  ASSETLIFECYCLEREPORT: '/reports/asset-lifecycle-report',
  ASSETREPORT: '/reports/asset-report',
  MAINTENANCEHISTORY: '/reports/maintenance-history',
  ASSETVALUATION: '/reports/asset-valuation',
  ASSETWORKFLOWHISTORY: '/reports/asset-workflow-history',
  SERIALNUMBERPRINT: '/serial-number-print',
  BULKSERIALNUMBERPRINT: '/bulk-serial-number-print',
  BREAKDOWNHISTORY: '/reports/breakdown-history',
  BREAKDOWNREOPENDETAILS: '/reports/breakdown-reopen-details',
  REOPENEDBREAKDOWNS: '/reports/reopened-breakdowns',
  USAGEBASEDASSETREPORT: '/reports/usage-based-asset',
  SLAREPORT: '/reports/sla-report',
  QAAUDITREPORT: '/reports/qa-audit-report',
  ADMINSETTINGS: '/admin-settings-view',
  MASTERDATA: '/master-data/vendors',
  ORGANIZATIONS: '/master-data/organizations',
  ASSETTYPES: '/master-data/asset-types',
  DEPARTMENTS: '/master-data/departments',
  BRANCHES: '/master-data/branches',
  ROLES: '/master-data/uploads',
  USERS: '/master-data/user-roles',
  USERROLES: '/master-data/job-roles',
  MAINTENANCESCHEDULE: '/maintenance-schedule-view',
  AUDITLOGS: '/audit-logs-view',
  AUDITLOGCONFIG: '/audit-log-config',
  COLUMNACCESSCONFIG: '/adminsettings/configuration/data-config',
  MAINTENANCECONFIG: '/adminsettings/configuration/maintenance-config',
  CERTIFICATIONS: '/certifications',
  TECHCERTUPLOAD: '/technician-certificates',
  TECHNICIANCERTIFICATES: '/technician-certificates',
  PROPERTIES: '/adminsettings/configuration/properties',
  BREAKDOWNREASONCODES: '/adminsettings/configuration/breakdown-reason-codes',
  ONETIMECRON: '/adminsettings/configuration/one-time-cron',
  TEXTMESSAGES: '/adminsettings/configuration/text-messages',
  JOBMONITOR: '/adminsettings/configuration/job-monitor',
  GROUPASSET: '/group-asset',
  SCRAPSALES: '/scrap-sales',
  SCRAPASSETS: '/scrap-assets',
  'EMPLOYEE TECH CERTIFICATION': '/technician-certificates',
  'HR/MANAGERAPPROVAL': '/tech-cert-approvals',
};

export function getAppPath(appId) {
  if (!appId) return null;
  const key = normalizeAppId(appId);
  return APP_ID_TO_PATH[key] || APP_ID_TO_PATH[appId] || null;
}
